### ISSUE TITLE
Fix Firebird test: conversion error from string "BOOLEAN"

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-db-tests#3]
```
Caused by: liquibase.exception.DatabaseException: conversion error from string "BOOLEAN" [SQLState:22018, ISC error code:335544334] [Failed SQL: (335544334) INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE)]
  at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:134)
  at liquibase.lockservice.StandardLockService.init(StandardLockService.java:126)
  at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:250)
  ... 115 more
Caused by: java.sql.SQLException: conversion error from string "BOOLEAN" [SQLState:22018, ISC error code:335544334]
  at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:539)
  at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:304)
  at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:140)
  at org.firebirdsql.gds.ng.wire.AbstractWireOperations.processOperation(AbstractWireOperations.java:204)
  at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readSingleResponse(AbstractWireOperations.java:171)
  at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readResponse(AbstractWireOperations.java:155)
  at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.readResponse(AbstractFbWireDatabase.java:211)
  at org.firebirdsql.gds.ng.wire.version10.V10Statement.execute(V10Statement.java:329)
  at org.firebirdsql.jdbc.FBStatement.internalExecute(FBStatement.java:869)
  at org.firebirdsql.jdbc.FBStatement.executeImpl(FBStatement.java:496)
  at org.firebirdsql.jdbc.FBStatement.execute(FBStatement.java:482)
  at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
  at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
  at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
  ... 120 more
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: conversion error from string "BOOLEAN"
```

**Comment by knstvk** [comment]
Try to remove this workaround code: https://github.com/Haulmont/jmix-db-tests/blob/main/src/test/java/io/jmix/dbtests/init/FirebirdInitializer.java#L30

**Comment by artemy63** [comment]
Fixed
